AUTH_TOO_MANY_REQUESTS = "요청이 너무 많습니다. 잠시 후 다시 시도해주세요."
AUTH_INVALID_CREDENTIALS = "아이디 또는 비밀번호가 틀렸습니다."
AUTH_WITHDRAWN = "탈퇴 처리된 계정입니다."
AUTH_SUSPENDED = "정지된 계정입니다. 관리자에게 문의하세요."
AUTH_LOGIN_RATE_LIMITED = "로그인 시도가 너무 많습니다. 잠시 후 다시 시도해주세요."
AUTH_EMAIL_EXISTS = "이미 등록된 이메일입니다."
AUTH_USERNAME_EXISTS = "이미 사용 중인 아이디입니다."
AUTH_NICKNAME_EXISTS = "이미 사용 중인 닉네임입니다."
AUTH_CREDENTIALS_REQUIRED = "아이디와 비밀번호를 입력해주세요."
AUTH_LOCKED_AFTER_FAILURES = "로그인 5회 실패로 계정이 잠금되었습니다."
AUTH_CONTACT_REQUIRED = "연락처 또는 이메일을 입력하세요."
AUTH_ACCOUNT_NOT_FOUND = "일치하는 계정을 찾지 못했습니다."
AUTH_REQUIRED_FIELDS = "필수 값을 입력해주세요."
AUTH_UNLOCK_CONTACT_REQUIRED = "아이디와 휴대폰/이메일이 필요합니다."
AUTH_UNLOCK_MISMATCH = "인증 정보가 일치하지 않습니다."
AUTH_CONTACT_VERIFY_REQUIRED = "연락처/이메일 인증이 필요합니다."
AUTH_PASSWORD_MISMATCH = "비밀번호가 올바르지 않습니다."

__all__ = [
	"AUTH_TOO_MANY_REQUESTS",
	"AUTH_INVALID_CREDENTIALS",
	"AUTH_WITHDRAWN",
	"AUTH_SUSPENDED",
	"AUTH_LOGIN_RATE_LIMITED",
	"AUTH_EMAIL_EXISTS",
	"AUTH_USERNAME_EXISTS",
	"AUTH_NICKNAME_EXISTS",
	"AUTH_CREDENTIALS_REQUIRED",
	"AUTH_LOCKED_AFTER_FAILURES",
	"AUTH_CONTACT_REQUIRED",
	"AUTH_ACCOUNT_NOT_FOUND",
	"AUTH_REQUIRED_FIELDS",
	"AUTH_UNLOCK_CONTACT_REQUIRED",
	"AUTH_UNLOCK_MISMATCH",
	"AUTH_CONTACT_VERIFY_REQUIRED",
	"AUTH_PASSWORD_MISMATCH",
]
