EVENT_VIEW_FORBIDDEN = "단원 이상만 이벤트를 확인할 수 있습니다."
EVENT_MANAGE_FORBIDDEN = "부단장 이상만 이벤트를 생성할 수 있습니다."
EVENT_UPDATE_FORBIDDEN = "부단장 이상만 이벤트를 수정할 수 있습니다."
EVENT_NOT_FOUND = "이벤트를 찾을 수 없습니다."
EVENT_VOTE_FORBIDDEN = "단원 이상만 투표할 수 있습니다."

EVENT_LOGIN_REQUIRED = "로그인이 필요합니다."
EVENT_MANAGE_ACTIVITY_REQUIRED = "임원 이상만 일정을 관리할 수 있습니다."
EVENT_ACTIVITY_NOT_FOUND = "활동을 찾을 수 없습니다."
EVENT_PARTICIPANTS_VIEW_FORBIDDEN = "단원 이상만 참여자 목록을 확인할 수 있습니다."
EVENT_JOIN_FORBIDDEN = "단원 이상만 참여 신청할 수 있습니다."
EVENT_CANCEL_FORBIDDEN = "단원 이상만 참여 취소할 수 있습니다."
EVENT_CAPACITY_FULL = "모집 정원이 마감되었습니다."
EVENT_ALREADY_APPLIED = "이미 신청한 활동입니다."
EVENT_NO_PARTICIPATION_HISTORY = "참가 신청 이력이 없습니다."
EVENT_ACCOUNT_STATUS_FORBIDDEN = "계정 상태로 인해 요청을 처리할 수 없습니다."
EVENT_NO_ACTIVITY_APPLICATION = "신청 내역이 없습니다."
EVENT_ACTIVITY_CANCELLED = "신청이 취소되었습니다."

__all__ = [
	"EVENT_VIEW_FORBIDDEN",
	"EVENT_MANAGE_FORBIDDEN",
	"EVENT_UPDATE_FORBIDDEN",
	"EVENT_NOT_FOUND",
	"EVENT_VOTE_FORBIDDEN",
	"EVENT_LOGIN_REQUIRED",
	"EVENT_MANAGE_ACTIVITY_REQUIRED",
	"EVENT_ACTIVITY_NOT_FOUND",
	"EVENT_PARTICIPANTS_VIEW_FORBIDDEN",
	"EVENT_JOIN_FORBIDDEN",
	"EVENT_CANCEL_FORBIDDEN",
	"EVENT_CAPACITY_FULL",
	"EVENT_ALREADY_APPLIED",
	"EVENT_NO_PARTICIPATION_HISTORY",
	"EVENT_ACCOUNT_STATUS_FORBIDDEN",
	"EVENT_NO_ACTIVITY_APPLICATION",
	"EVENT_ACTIVITY_CANCELLED",
]
