FILE_MEMBER_REQUIRED_UPLOAD = "단원 이상만 파일을 업로드할 수 있습니다."
FILE_MEMBER_REQUIRED_ACCESS = "단원 이상만 접근할 수 있습니다."
FILE_POST_NOT_FOUND = "게시글을 찾을 수 없습니다."
FILE_INVALID_PATH = "Invalid path"
FILE_NOT_FOUND = "파일을 찾을 수 없습니다."
FILE_STORED_MISSING = "저장된 파일이 없습니다."
FILE_EXPIRES_INVALID = "expires_at은 ISO 형식이어야 합니다."
FILE_UPLOAD_PROCESS_FAILED = "파일 처리에 실패했습니다."
FILE_GALLERY_THUMB_FAILED = "갤러리 썸네일 생성에 실패했습니다."

__all__ = [
	"FILE_MEMBER_REQUIRED_UPLOAD",
	"FILE_MEMBER_REQUIRED_ACCESS",
	"FILE_POST_NOT_FOUND",
	"FILE_INVALID_PATH",
	"FILE_NOT_FOUND",
	"FILE_STORED_MISSING",
	"FILE_EXPIRES_INVALID",
	"FILE_UPLOAD_PROCESS_FAILED",
	"FILE_GALLERY_THUMB_FAILED",
]
