POSTS_OPERATOR_REQUIRED = "운영진 이상만 수정할 수 있습니다."
POST_NOT_FOUND = "게시글을 찾을 수 없습니다."
POST_INVALID_CATEGORY = "type(category)은 notice|review|recruit|qna|gallery만 허용합니다."
POST_TITLE_REQUIRED = "title은 필수입니다."
POST_PUBLISH_AT_INVALID = "publish_at은 ISO 형식이어야 합니다."
POST_SUSPENDED_FORBIDDEN = "정지된 계정은 게시글을 작성할 수 없습니다."
POST_AUTHOR_OR_EXEC_REQUIRED = "작성자 또는 운영진만 수정/삭제할 수 있습니다."
POST_CATEGORY_REQUIRED = "category는 필수입니다."
POST_ALREADY_RECOMMENDED = "이미 추천하셨습니다."
POST_TEMPLATE_UNSUPPORTED = "지원하지 않는 템플릿입니다."
POST_ABOUT_SECTION_INVALID = "유효하지 않은 소개 섹션 키입니다."
POST_CONTENT_BLOCK_INVALID = "유효하지 않은 콘텐츠 블록 키입니다."
POST_EXEC_REQUIRED = "운영진 이상만 수정할 수 있습니다."
POST_ADMIN_ONLY_BACKGROUND_IMAGE = "운영진만 배경 이미지를 수정할 수 있습니다."
POST_IMAGE_FILE_REQUIRED = "이미지 파일이 필요합니다."
POST_IMAGE_FILE_TYPE_INVALID = "소개 섹션 이미지는 jpg/jpeg/png/webp/gif만 업로드할 수 있습니다."
POST_FILE_PROCESS_FAILED = "파일 처리에 실패했습니다."
POST_HOME_STATS_ADMIN_ONLY = "운영진만 홈 통계를 수정할 수 있습니다."
POST_HERO_BACKGROUND_ADMIN_ONLY = "운영진만 홈 배경 설정을 수정할 수 있습니다."

__all__ = [
	"POSTS_OPERATOR_REQUIRED",
	"POST_NOT_FOUND",
	"POST_INVALID_CATEGORY",
	"POST_TITLE_REQUIRED",
	"POST_PUBLISH_AT_INVALID",
	"POST_SUSPENDED_FORBIDDEN",
	"POST_AUTHOR_OR_EXEC_REQUIRED",
	"POST_CATEGORY_REQUIRED",
	"POST_ALREADY_RECOMMENDED",
	"POST_TEMPLATE_UNSUPPORTED",
	"POST_ABOUT_SECTION_INVALID",
	"POST_CONTENT_BLOCK_INVALID",
	"POST_EXEC_REQUIRED",
	"POST_ADMIN_ONLY_BACKGROUND_IMAGE",
	"POST_IMAGE_FILE_REQUIRED",
	"POST_IMAGE_FILE_TYPE_INVALID",
	"POST_FILE_PROCESS_FAILED",
	"POST_HOME_STATS_ADMIN_ONLY",
	"POST_HERO_BACKGROUND_ADMIN_ONLY",
]
