ROLE_REQUEST_INVALID_TRANSITION = "요청 가능한 역할 전환이 아닙니다."
ROLE_REQUEST_NOT_FOUND = "요청을 찾을 수 없습니다."
ROLE_REQUEST_ALREADY_DECIDED = "이미 처리된 요청입니다."
ROLE_REQUEST_PENDING_EXISTS = "이미 처리 대기 중인 요청이 있습니다."
ROLE_REQUEST_VICE_LEADER_REQUIRED = "부단장 이상만 접근할 수 있습니다."

__all__ = [
	"ROLE_REQUEST_INVALID_TRANSITION",
	"ROLE_REQUEST_NOT_FOUND",
	"ROLE_REQUEST_ALREADY_DECIDED",
	"ROLE_REQUEST_PENDING_EXISTS",
	"ROLE_REQUEST_VICE_LEADER_REQUIRED",
]
